spring:
  datasource:
    name:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.0.200:1521:orcl
    username: stzlpt
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

#Mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.genius.study.model
